=== angelagm/XML-Esquemas/ejercicio 1_1/1_1_5sch.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="paises">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="pais" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="pais">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nombre" type="xs:string"/>
        <xs:element name="unionEuropea" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="otan" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== angelagm/XML-Esquemas/ejercicio 1_1/5_paises.xml
<?xml version="1.0" encoding="UTF-8"?>
<paises xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///E:/Marcas/Git/XML-Esquemas/ejercicio%201_1/1_1_5sch.xsd">
  <pais>
    <nombre>España</nombre>
    <unionEuropea/>
    <otan/>
  </pais>
  <pais>
    <nombre>Noruega</nombre>
    <otan/>
  </pais>
  <pais>
    <nombre>Austria</nombre>
    <unionEuropea/>
  </pais>
  <pais>
    <nombre>Brasil</nombre>
  </pais>
</paises>
